### ISSUE TITLE
Help with mod.cpk

### ISSUE THREAD

**Issue by minewell15** [DeathChaos25/PQ_Patches#1]
I'm sorry in advance, I've never modded anything on the 3ds, just basic homebrew and cia. stuff.  Also sorry that I am posting an issue on a relatively old thread. Trying to get this to work for PQ2 game is US, I have all files in the correct luma folder with the correct title ID but I just can't quite understand how the mod.cpk works. I understand that the mod.cpk attached is a dummy file with a empty txt in it. But I have no idea how I make my own. I tried everything, I tried using magikoopa, couldn't get that to work, I tried simply booting without the mod.cpk file, I tried with the dummy file, but no matter what the game crashes at boot. I'm sorry again, but I really just can't get this to work.

**Comment by rabbitgirlkris** [comment]
you need an app called [mod compendium](https://github.com/TGEnigma/Mod-Compendium/releases/), the longer names patch doesn't need a new mod.cpk, it's used for playing other mods, which most of are in [here](https://shrinefox.com/browse?type=mod&game=PQ2)

**Comment by joker31802** [comment]
I have a question

**Comment by joker31802** [comment]
It's relating to this mod

**Comment by joker31802** [comment]
Where do I send questions
