### ISSUE TITLE
version without custom names patch

### ISSUE THREAD

**Issue by rabbitgirlkris** [DeathChaos25/PQ_Patches#2]
adding a version without the custom names patch would be a good idea, the people who want a faster way to test out their mods without repacking the entire data.cpk aren't always the same that would want longer names, i'm forced to use names i don't really like at all just so i can save time when testing out my mods

**Comment by zarroboogs** [comment]
I added [PQ_Patches-v1.0.1-ModCpk.7z](/DeathChaos25/PQ_Patches/releases/download/v1.0.1/PQ_Patches-v1.0.1-ModCpk.7z) to the latest release, it contains files with only the `ModCpk` patch applied (for both PQ1 and PQ2). Please test and see if it works for you.

**Comment by rabbitgirlkris** [comment]
it does work! ty
